jdk: 17
android: true
# configuration file for building snapshots and releases with jitpack.io
before_install:
  - ./scripts/prepareJitpackEnvironment.sh
install:
  - FILE="-Dfile=toasty.aar"
  - mvn install:install-file $FILE -DgroupId=com.github.alexvarboffin-atif -DartifactId=com-atifqamar-toasty -Dversion=1.1.1 -Dpackaging=aar -DgeneratePom=true