jdk: 17
android: true
# configuration file for building snapshots and releases with jitpack.io
#before_install:
#  - ./scripts/prepareJitpackEnvironment.sh
install:
  - FILE="-Dfile=Toasty.aar" #com-atifqamar-customtoast.aar
  - mvn install:install-file $FILE -DgroupId=com.github.alexvarboffin -DartifactId=Toasty -Dversion=1.1.1 -Dpackaging=aar -DgeneratePom=true